import type { SceneTemplate } from "./templates";

// ============================================
// PixelMuse 预设模板数据
// 共 20 个模板，覆盖 4 大场景分类
// ============================================

export const SCENE_TEMPLATES: SceneTemplate[] = [
  // ============================================
  // 电商营销 (ecommerce) — 5 个模板
  // ============================================
  {
    id: "ecom-product-white",
    name: "产品白底图",
    category: "ecommerce",
    type: "image",
    description: "干净白底，适合淘宝/京东商品主图",
    coverImage: "/templates/ecom-white-bg.jpg",
    promptTemplate: "A professional product photography of {product} on a pure white background, studio lighting, high detail, commercial photography, {style}",
    variables: [
      { key: "product", label: "产品描述", type: "text", placeholder: "例: 一双白色运动鞋", required: true },
      { key: "style", label: "拍摄风格", type: "select", options: ["极简风", "柔光棚拍", "硬光质感", "高级感"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "high" },
    tags: ["白底图", "商品主图", "电商"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "ecom-product-scene",
    name: "产品场景图",
    category: "ecommerce",
    type: "image",
    description: "产品 + 生活场景，提升购买欲",
    coverImage: "/templates/ecom-scene.jpg",
    promptTemplate: "A lifestyle product photography of {product} in a {scene} setting, warm natural lighting, aesthetic composition, {mood} mood",
    variables: [
      { key: "product", label: "产品描述", type: "text", placeholder: "例: 一杯拿铁咖啡", required: true },
      { key: "scene", label: "场景", type: "select", options: ["咖啡厅", "家居客厅", "户外花园", "办公桌面", "厨房台面"], required: true },
      { key: "mood", label: "氛围", type: "select", options: ["温馨", "清新", "高级", "活力"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "4:3", quality: "high" },
    tags: ["场景图", "生活方式", "电商"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "ecom-promo-poster",
    name: "促销海报",
    category: "ecommerce",
    type: "image",
    description: "大促活动、节日促销海报",
    coverImage: "/templates/ecom-promo.jpg",
    promptTemplate: "A vibrant promotional poster for {event}, featuring {product}, {color_scheme} color scheme, bold typography area, festive and eye-catching design, commercial graphic design",
    variables: [
      { key: "event", label: "活动名称", type: "text", placeholder: "例: 618年中大促", required: true },
      { key: "product", label: "产品类型", type: "text", placeholder: "例: 美妆护肤品", required: true },
      { key: "color_scheme", label: "配色", type: "select", options: ["红金喜庆", "蓝白清爽", "粉紫浪漫", "黑金高端"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "9:16", quality: "high" },
    tags: ["促销", "海报", "活动"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "ecom-product-video",
    name: "产品展示视频",
    category: "ecommerce",
    type: "video",
    description: "360度产品展示，适合商品详情页",
    coverImage: "/templates/ecom-video.jpg",
    promptTemplate: "A smooth 360-degree rotating product showcase video of {product}, studio lighting, white background, slow rotation, professional commercial video, {style}",
    variables: [
      { key: "product", label: "产品描述", type: "text", placeholder: "例: 一瓶红色香水", required: true },
      { key: "style", label: "视频风格", type: "select", options: ["简约商务", "光影质感", "柔光梦幻"], required: false },
    ],
    presets: { model: "sora-2", aspectRatio: "16:9", duration: 10 },
    tags: ["产品视频", "360展示", "电商"],
    exampleOutputs: [],
    credits: 2,
    difficulty: "easy",
  },
  {
    id: "ecom-food-photo",
    name: "美食摄影",
    category: "ecommerce",
    type: "image",
    description: "精美食物照片，适合外卖/餐饮",
    coverImage: "/templates/ecom-food.jpg",
    promptTemplate: "Delicious food photography of {food}, {style} style, overhead shot, beautiful plating, {background} background, appetizing and inviting, professional food photography",
    variables: [
      { key: "food", label: "食物描述", type: "text", placeholder: "例: 一份日式寿司拼盘", required: true },
      { key: "style", label: "摄影风格", type: "select", options: ["日系清新", "暗调质感", "明亮活泼", "中式古风"], required: false },
      { key: "background", label: "背景", type: "select", options: ["木质桌面", "大理石台面", "纯色背景", "餐厅场景"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "high" },
    tags: ["美食", "餐饮", "外卖"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },

  // ============================================
  // 社交媒体 (social-media) — 5 个模板
  // ============================================
  {
    id: "social-xiaohongshu",
    name: "小红书种草图",
    category: "social-media",
    type: "image",
    description: "精致种草风格，适合小红书分享",
    coverImage: "/templates/social-xhs.jpg",
    promptTemplate: "A trendy lifestyle flat lay photo featuring {product}, aesthetic {style} style, soft natural lighting, instagram-worthy composition, pastel tones, cozy and inviting vibe",
    variables: [
      { key: "product", label: "分享内容", type: "text", placeholder: "例: 护肤品套装和鲜花", required: true },
      { key: "style", label: "风格", type: "select", options: ["ins风", "日系", "韩系", "法式复古"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "3:4", quality: "high" },
    tags: ["小红书", "种草", "分享"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "social-moments",
    name: "朋友圈配图",
    category: "social-media",
    type: "image",
    description: "精美生活照，朋友圈获赞神器",
    coverImage: "/templates/social-moments.jpg",
    promptTemplate: "A beautiful {scene} photograph, {style} aesthetic, golden hour lighting, {mood} atmosphere, high quality lifestyle photography, perfect for social media sharing",
    variables: [
      { key: "scene", label: "场景", type: "text", placeholder: "例: 海边日落", required: true },
      { key: "style", label: "风格", type: "select", options: ["文艺清新", "电影感", "胶片质感", "梦幻柔光"], required: false },
      { key: "mood", label: "氛围", type: "select", options: ["浪漫", "治愈", "活力", "安静"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "high" },
    tags: ["朋友圈", "生活照", "配图"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "social-douyin-cover",
    name: "抖音封面",
    category: "social-media",
    type: "image",
    description: "9:16竖版封面，吸引点击",
    coverImage: "/templates/social-douyin.jpg",
    promptTemplate: "A captivating vertical thumbnail image for a short video about {topic}, {style} design, vibrant colors, eye-catching composition, text area at top, dynamic and energetic",
    variables: [
      { key: "topic", label: "视频主题", type: "text", placeholder: "例: 美食探店", required: true },
      { key: "style", label: "封面风格", type: "select", options: ["活力撞色", "简约大气", "复古滤镜", "科技感"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "9:16", quality: "high" },
    tags: ["抖音", "封面", "短视频"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "social-short-video",
    name: "短视频素材",
    category: "social-media",
    type: "video",
    description: "抖音/快手短视频素材",
    coverImage: "/templates/social-video.jpg",
    promptTemplate: "A vertical short-form video clip of {content}, {style} cinematic style, dynamic camera movement, engaging and visually stunning, perfect for social media, {mood} mood",
    variables: [
      { key: "content", label: "视频内容", type: "text", placeholder: "例: 城市夜景航拍", required: true },
      { key: "style", label: "视频风格", type: "select", options: ["电影感", "Vlog风", "快节奏剪辑", "慢动作"], required: false },
      { key: "mood", label: "氛围", type: "select", options: ["热血", "治愈", "震撼", "日常"], required: false },
    ],
    presets: { model: "sora-2", aspectRatio: "9:16", duration: 10 },
    tags: ["短视频", "抖音", "快手"],
    exampleOutputs: [],
    credits: 2,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "social-avatar",
    name: "社交头像",
    category: "social-media",
    type: "image",
    description: "个性化社交媒体头像",
    coverImage: "/templates/social-avatar.jpg",
    promptTemplate: "A stylish avatar portrait in {style} art style, {subject}, {color} color palette, clean background, suitable for social media profile picture, high quality digital art",
    variables: [
      { key: "subject", label: "形象描述", type: "text", placeholder: "例: 一个戴眼镜的女生", required: true },
      { key: "style", label: "画风", type: "select", options: ["动漫二次元", "3D卡通", "赛博朋克", "水彩手绘", "像素风"], required: true },
      { key: "color", label: "主色调", type: "select", options: ["暖色系", "冷色系", "马卡龙", "黑白灰"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "high" },
    tags: ["头像", "社交", "个性化"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },

  // ============================================
  // 商务办公 (business) — 5 个模板
  // ============================================
  {
    id: "biz-ppt-image",
    name: "PPT 配图",
    category: "business",
    type: "image",
    description: "16:9 商务风格，PPT/演示必备",
    coverImage: "/templates/biz-ppt.jpg",
    promptTemplate: "A professional business illustration for a presentation about {topic}, {style} design style, clean and modern, suitable for PowerPoint slide, {color} color scheme, corporate aesthetic",
    variables: [
      { key: "topic", label: "演示主题", type: "text", placeholder: "例: 数据分析与增长", required: true },
      { key: "style", label: "设计风格", type: "select", options: ["扁平插画", "3D渲染", "等距视图", "数据可视化"], required: false },
      { key: "color", label: "配色", type: "select", options: ["蓝色专业", "绿色环保", "橙色活力", "紫色创新"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "16:9", quality: "high" },
    tags: ["PPT", "演示", "商务"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "biz-wechat-cover",
    name: "公众号封面",
    category: "business",
    type: "image",
    description: "公众号文章封面图，吸引阅读",
    coverImage: "/templates/biz-wechat.jpg",
    promptTemplate: "A visually appealing article header image about {topic}, {style} design, wide format 2.35:1, with space for text overlay, {mood} tone, professional yet engaging",
    variables: [
      { key: "topic", label: "文章主题", type: "text", placeholder: "例: 2024年AI发展趋势", required: true },
      { key: "style", label: "风格", type: "select", options: ["科技感", "简约文艺", "商务正式", "创意趣味"], required: false },
      { key: "mood", label: "调性", type: "select", options: ["专业严肃", "轻松活泼", "前沿科技", "温暖亲和"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "16:9", quality: "high" },
    tags: ["公众号", "封面", "自媒体"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "biz-logo",
    name: "品牌 Logo",
    category: "business",
    type: "image",
    description: "简约品牌Logo设计",
    coverImage: "/templates/biz-logo.jpg",
    promptTemplate: "A minimalist brand logo design for {brand}, {style} style, {color} color palette, clean vector-like design, modern typography, professional and memorable, white background",
    variables: [
      { key: "brand", label: "品牌/公司名", type: "text", placeholder: "例: 星辰科技", required: true },
      { key: "style", label: "Logo风格", type: "select", options: ["极简几何", "字母组合", "图标+文字", "手写体"], required: true },
      { key: "color", label: "品牌色", type: "select", options: ["蓝色稳重", "绿色自然", "红色活力", "黑金高端", "多彩渐变"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "high" },
    tags: ["Logo", "品牌", "设计"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "medium",
  },
  {
    id: "biz-intro-video",
    name: "产品介绍视频",
    category: "business",
    type: "video",
    description: "企业宣传/产品介绍片头",
    coverImage: "/templates/biz-intro.jpg",
    promptTemplate: "A professional corporate introduction video about {topic}, {style} cinematic style, smooth camera movements, modern office environment, {mood} and inspiring, business promotional video",
    variables: [
      { key: "topic", label: "介绍主题", type: "text", placeholder: "例: SaaS产品功能演示", required: true },
      { key: "style", label: "视频风格", type: "select", options: ["科技感", "温馨叙事", "快节奏", "大气磅礴"], required: false },
      { key: "mood", label: "基调", type: "select", options: ["专业可信", "创新前沿", "温暖人文"], required: false },
    ],
    presets: { model: "sora-2", aspectRatio: "16:9", duration: 10 },
    tags: ["宣传片", "企业", "介绍"],
    exampleOutputs: [],
    credits: 2,
    difficulty: "easy",
  },
  {
    id: "biz-namecard",
    name: "名片设计",
    category: "business",
    type: "image",
    description: "个性化名片设计模板",
    coverImage: "/templates/biz-namecard.jpg",
    promptTemplate: "A modern business card design for {name}, {title} at {company}, {style} design aesthetic, {color} color scheme, clean layout with space for contact info, professional and elegant",
    variables: [
      { key: "name", label: "姓名", type: "text", placeholder: "例: 张三", required: true },
      { key: "title", label: "职位", type: "text", placeholder: "例: 产品总监", required: true },
      { key: "company", label: "公司名", type: "text", placeholder: "例: 创新科技有限公司", required: true },
      { key: "style", label: "风格", type: "select", options: ["极简现代", "创意几何", "传统稳重", "科技未来"], required: false },
      { key: "color", label: "配色", type: "select", options: ["黑白经典", "蓝色专业", "绿色环保", "渐变潮流"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "16:9", quality: "high" },
    tags: ["名片", "商务", "设计"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },

  // ============================================
  // 个人创作 (personal) — 5 个模板
  // ============================================
  {
    id: "personal-portrait",
    name: "AI 写真",
    category: "personal",
    type: "image",
    description: "AI生成个性化写真照片",
    coverImage: "/templates/personal-portrait.jpg",
    promptTemplate: "A stunning portrait photograph of {subject}, {style} photography style, {lighting} lighting, {background} background, professional quality, artistic composition, high detail",
    variables: [
      { key: "subject", label: "人物描述", type: "text", placeholder: "例: 一个长发女生穿着白色连衣裙", required: true },
      { key: "style", label: "写真风格", type: "select", options: ["清新自然", "复古胶片", "日系小清新", "欧美时尚", "古风汉服"], required: true },
      { key: "lighting", label: "光线", type: "select", options: ["柔和自然光", "金色夕阳", "蓝调冷光", "影棚灯光"], required: false },
      { key: "background", label: "背景", type: "select", options: ["户外花田", "咖啡厅", "城市街头", "海边", "森林"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "3:4", quality: "high" },
    tags: ["写真", "人像", "艺术照"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
    popular: true,
  },
  {
    id: "personal-wallpaper",
    name: "手机壁纸",
    category: "personal",
    type: "image",
    description: "精美手机壁纸，独一无二",
    coverImage: "/templates/personal-wallpaper.jpg",
    promptTemplate: "A stunning vertical wallpaper of {scene}, {style} art style, {color} color palette, highly detailed, beautiful composition, 4K quality, suitable for phone wallpaper",
    variables: [
      { key: "scene", label: "壁纸内容", type: "text", placeholder: "例: 星空下的雪山", required: true },
      { key: "style", label: "风格", type: "select", options: ["写实摄影", "动漫插画", "水彩画风", "赛博朋克", "极简抽象"], required: false },
      { key: "color", label: "色调", type: "select", options: ["暖色调", "冷色调", "黑暗系", "清新明亮", "梦幻渐变"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "9:16", quality: "high" },
    tags: ["壁纸", "手机", "桌面"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "personal-emoji",
    name: "表情包",
    category: "personal",
    type: "image",
    description: "自定义趣味表情包",
    coverImage: "/templates/personal-emoji.jpg",
    promptTemplate: "A cute and funny sticker/emoji of {character} with {expression} expression, {style} art style, simple clean background, bold outlines, expressive and exaggerated, suitable for chat sticker",
    variables: [
      { key: "character", label: "角色", type: "text", placeholder: "例: 一只橘猫", required: true },
      { key: "expression", label: "表情/动作", type: "select", options: ["开心大笑", "生气鼓腮", "委屈巴巴", "比心卖萌", "加油打气", "偷偷摸鱼"], required: true },
      { key: "style", label: "画风", type: "select", options: ["可爱卡通", "搞怪涂鸦", "像素风", "3D立体"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "1:1", quality: "standard" },
    tags: ["表情包", "贴纸", "趣味"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "personal-greeting",
    name: "节日贺卡",
    category: "personal",
    type: "image",
    description: "节日祝福贺卡，传递温暖",
    coverImage: "/templates/personal-greeting.jpg",
    promptTemplate: "A beautiful {festival} greeting card design, featuring {elements}, {style} illustration style, {color} color palette, festive and warm, with space for greeting text, high quality digital art",
    variables: [
      { key: "festival", label: "节日", type: "select", options: ["春节", "中秋", "圣诞", "生日", "情人节", "新年", "母亲节", "父亲节"], required: true },
      { key: "elements", label: "画面元素", type: "text", placeholder: "例: 灯笼和烟花", required: false },
      { key: "style", label: "风格", type: "select", options: ["国风水墨", "现代插画", "复古怀旧", "童趣卡通"], required: false },
      { key: "color", label: "配色", type: "select", options: ["红金喜庆", "清新淡雅", "暖色温馨", "缤纷多彩"], required: false },
    ],
    presets: { model: "flux-1", aspectRatio: "4:3", quality: "high" },
    tags: ["贺卡", "节日", "祝福"],
    exampleOutputs: [],
    credits: 1,
    difficulty: "easy",
  },
  {
    id: "personal-cinematic-clip",
    name: "电影感短片",
    category: "personal",
    type: "video",
    description: "电影质感视频片段，记录美好瞬间",
    coverImage: "/templates/personal-cinematic.jpg",
    promptTemplate: "A cinematic video clip of {scene}, {style} filmmaking style, beautiful color grading, {camera} camera movement, atmospheric and immersive, film-like quality, {mood} mood",
    variables: [
      { key: "scene", label: "画面描述", type: "text", placeholder: "例: 雨中的城市街道", required: true },
      { key: "style", label: "电影风格", type: "select", options: ["文艺片", "科幻片", "纪录片", "MV风格"], required: false },
      { key: "camera", label: "镜头运动", type: "select", options: ["缓慢推进", "航拍俯冲", "跟随拍摄", "固定机位"], required: false },
      { key: "mood", label: "基调", type: "select", options: ["孤独", "温暖", "壮丽", "神秘"], required: false },
    ],
    presets: { model: "sora-2", aspectRatio: "16:9", duration: 10 },
    tags: ["电影感", "短片", "创作"],
    exampleOutputs: [],
    credits: 2,
    difficulty: "medium",
  },
];
